In [18]:
#Question 1
#Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

import numpy as np
list=[1,2,3,4,5,6,7]
a=np.array(list)
print("The one dimensional array is:",a)

The one dimensional array is: [1 2 3 4 5 6 7]


In [20]:
#Question 2
#Create a 3x3 matrix with values ranging from 2 to 10.

a=np.arange(2,11).reshape(3,3)
print("The 3x3 matrix with values ranging from 2 to 10 is:\n",a)

The 3x3 matrix with values ranging from 2 to 10 is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [22]:
#Question 3
#Write a Python program to create a null vector of size 10 and update sixth value to 11.

a=np.zeros(10,dtype=int)
print("The null vector of size is:",a)
a[6]=11
print("The array after updating the 6th value is:",a)

The null vector of size is: [0 0 0 0 0 0 0 0 0 0]
The array after updating the 6th value is: [ 0  0  0  0  0  0 11  0  0  0]


In [7]:
#Question 4
#Write a Python program to create a array with values ranging from 12 to 38.

a=np.arange(12,39)
print("The array with values ranging from 12 to 38 is: ",a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37 38]


In [8]:
#Question 5
#Write a Python program to reverse an array (first element becomes last).

b1=a[-1::-1]
print("The array after reversing the value is: ",b1)

[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [29]:
#Question 6
#Write a Python program to an int array converted to a float type.

a=np.arange(8)
print("The array with int value is:",a)
b1=a.astype(float)
print("The array with float value is:",b1)

[0 1 2 3 4 5 6 7]
[ 0.  1.  2.  3.  4.  5.  6.  7.]


In [16]:
#Question 7
#Write a Python program to create a 2d array (5x5) with 1 on the border and 0 inside.

a=np.ones(25).reshape(5,5)
b=a[1:4,1:4]=0
print(a)
#print(b)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [25]:
#Question 8
#Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

a=np.arange(8)
print("the array is:",a)
print("The size of array is: ",a.size)
print("The size of elements in bytes is: ",a.itemsize)
print("The total bytes consumed is: ",a.nbytes)

the array is: [0 1 2 3 4 5 6 7]
The size of array is:  8
The size of elements in bytes is:  4
The total bytes consumed is:  32


In [85]:
#Question 9
#Write a Python program to create a function cube which cubes all the elements of an array.

#b=np.empty(4,dtype=int)
#b=np.array([])
b=[]
def cube(a):
    for i in range(0,len(a)):
        b.append(a[i]**3)
        #print("hii")
    return np.array(b)

a=np.array([1,2,3,4])
print("The cube of elemnts of array is: ",cube(a))

The cube of elemnts of array is:  [ 1  8 27 64]


In [47]:
#Question 10
#Write a Python program to how to add an extra column to an numpy array.

a=np.arange(2,10).reshape(2,4)
print("The array is:\n",a)
b=np.arange(10,12).reshape(2,1)
print("The array is:\n",b)
c=np.append(a,b)
print("The resulting array is:\n",c.reshape(2,5))

The array is:
 [[2 3 4 5]
 [6 7 8 9]]
The array is:
 [[10]
 [11]]
The resulting array is:
 [[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


In [51]:
#Question 11
#Write a Python program to remove the negative values in a numpy array with 0.

a=np.array([1,2,3,-4,5,-6])
for x in range(0,len(a)):
    if a[x]<0:
        a[x]=0
print(a)

[1 2 3 0 5 0]


In [58]:
#Question 12
# Extend the array by repeating the current elements, 3 times.

b=[]
a=np.array([1,2,3,4])
for x in range (4):
      b.append(a)
print("The array after extending it by 3 times:",np.array(b))


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [59]:
#Question 14
#Write a Python program compare two arrays using numpy.

a=np.array([1,2,6])
b=np.array([1,1,4])

c=np.greater(a,b)
print("The output after comparing two arrays is:",c)

[False  True  True]


In [10]:
#Question 15
#Create a 3x5 array with random elements. Reshape this into 5x3.  

#import numpy as np
a=np.random.rand(15).reshape(3,5)
print("The array with random elements is:\n ",a)

The array with random elements is:
  [[ 0.56678856  0.78488877  0.98046941  0.35414078  0.52073748]
 [ 0.86375051  0.68048408  0.95825721  0.44201966  0.14091402]
 [ 0.32599704  0.45393163  0.55483732  0.92800111  0.72984893]]


In [86]:
a=np.eye(6)
b=np.array([a]*6)
print(b.shape)
print(b)

(6, 6, 6)
[[[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]


In [51]:
#Question 17.A.1)
#Find the mean, median, mode and standard deviation for marks of each subject

from scipy import stats
marks=np.array([[15,20,25,12],[45,50,50,48],[8,7,3,2],[28,32,40,39]])

mean=np.mean(marks,axis=0)
list1=["Maths","Physics","Chemistry","Sciology","English"]
for i in range (4):
    print("The mean  for %s is : %g "%(list1[i],mean[i]))

print("\n")

median=np.median(marks,axis=0)
for i in range (4):
    print("The median  for %s is: %g"%(list1[i],median[i]))

print("\n")

std=np.std(marks,axis=0)
for i in range (4):
    print("The standard deviation  for %s is: %g"%(list1[i],std[i]))

print("\n")

m=stats.mode(marks,axis=0)
print("The mode for subjects is:",m[0])


The mean  for Maths is : 24 
The mean  for Physics is : 27.25 
The mean  for Chemistry is : 29.5 
The mean  for Sciology is : 25.25 


The median  for Maths is: 21.5
The median  for Physics is: 26
The median  for Chemistry is: 32.5
The median  for Sciology is: 25.5


The standard deviation  for Maths is: 14.089
The standard deviation  for Physics is: 15.8331
The standard deviation  for Chemistry is: 17.6989
The standard deviation  for Sciology is: 18.8597


The mode for subjects is: [[8 7 3 2]]


In [35]:
#Question 17.A.2)
#What is the minimum and maximum of each subject?

min=np.min(marks,axis=0)
for i in range (4):
    print("The minimum  for %s is : %g "%(list1[i],min[i]))
print("\n") 

max=np.max(marks,axis=0)
for i in range (4):
    print("The maximum  for %s is : %g "%(list1[i],max[i]))
print("\n") 

The minimum  for Maths is : 8 
The minimum  for Physics is : 7 
The minimum  for Chemistry is : 3 
The minimum  for Sciology is : 2 


The maximum  for Maths is : 45 
The maximum  for Physics is : 50 
The maximum  for Chemistry is : 50 
The maximum  for Sciology is : 48 




In [82]:
#Question 17.A.3)
#Print the subject in  each student good at and poor at ?

print("Rajesh is good in %s and bad in %s"%(list1[marks[0].argmax()],list1[marks[0].argmin()]))
print("Rima is good in %s and bad in %s"%(list1[marks[1].argmax()],list1[marks[2].argmin()]))
print("Ram is good in %s and bad in %s"%(list1[marks[2].argmax()],list1[marks[2].argmin()]))
print("Joseph is good in %s and bad in %s"%(list1[marks[3].argmax()],list1[marks[3].argmin()]))


Rajesh is good in Chemistry and bad in Sciology
Rima is good in Physics and bad in Sciology
Ram is good in Maths and bad in Sciology
Joseph is good in Chemistry and bad in Maths


In [40]:
#Question 17.A.4)
#What is the overall class mean, mode, median and standard deviation

print("The mean for overall class is:",np.mean(marks))
print("The median for overall class is:",np.median(marks))
print("The standard deviation for overall class is:",np.std(marks))
m=stats.mode(marks,axis=0)
print("The mode for overall class is:",m[0])

The mean for overall class is: 26.5
The median for overall class is: 26.5
The standard deviation for overall class is: 16.8485904455
The mode for overall class is: [[8 7 3 2]]


In [55]:
#Question 17.B)
#Teacher just announced the marks of English. They are 40, 49, 10 and 35 for eah student.
#Re-calculate all subparts of A.

eng=np.array([40,49,10,35]).reshape(4,1)
marks1=np.append(marks,eng,axis=1)
print("The marks after adding english marks:\n",marks1)

print("\n")
print("The mean for English is: ",np.mean(marks1,axis=0))
print("The median for English is: ",np.median(marks1,axis=0))
print("The Standard Deviation for English is: ",np.std(marks1,axis=0))
m=stats.mode(marks,axis=0)
print("The mode for English is:",m[0])


The marks after adding english marks:
 [[15 20 25 12 40]
 [45 50 50 48 49]
 [ 8  7  3  2 10]
 [28 32 40 39 35]]


The mean for English is:  [ 24.    27.25  29.5   25.25  33.5 ]
The median for English is:  [ 21.5  26.   32.5  25.5  37.5]
The Standard Deviation for English is:  [ 14.0890028   15.83311403  17.69887002  18.85967921  14.46547614]
The mode for English is: [[8 7 3 2]]


In [61]:
#Question 17.c)
#A new student joined the class. For the time being, the scores are going to be zero for each student. 
#Re-calculate A again with the new student.

new=np.array([0,0,0,0,0]).reshape(1,5)
marks2=np.append(marks1,new,axis=0)
print("The array after adding the new student marks:\n",marks2)

mean=np.mean(marks2,axis=0)
list1=["Maths","Physics","Chemistry","Sciology","English"]
for i in range (5):
    print("The mean  for %s is : %g "%(list1[i],mean[i]))

print("\n")

median=np.median(marks2,axis=0)
for i in range (5):
    print("The median  for %s is: %g"%(list1[i],median[i]))

print("\n")

std=np.std(marks2,axis=0)
for i in range (5):
    print("The standard deviation  for %s is: %g"%(list1[i],std[i]))

print("\n")

m=stats.mode(marks2,axis=0)
print("The mode for subjects is:",m[0])

min=np.min(marks2,axis=0)
for i in range (5):
    print("The minimum  for %s is : %g "%(list1[i],min[i]))
print("\n") 

max=np.max(marks2,axis=0)
for i in range (5):
    print("The maximum  for %s is : %g "%(list1[i],max[i]))
print("\n") 



The array after adding the new student marks:
 [[15 20 25 12 40]
 [45 50 50 48 49]
 [ 8  7  3  2 10]
 [28 32 40 39 35]
 [ 0  0  0  0  0]]
The mean  for Maths is : 19.2 
The mean  for Physics is : 21.8 
The mean  for Chemistry is : 23.6 
The mean  for Sciology is : 20.2 
The mean  for English is : 26.8 


The median  for Maths is: 15
The median  for Physics is: 20
The median  for Chemistry is: 25
The median  for Sciology is: 12
The median  for English is: 35


The standard deviation  for Maths is: 15.8417
The standard deviation  for Physics is: 17.8706
The standard deviation  for Chemistry is: 19.7444
The standard deviation  for Sciology is: 19.6611
The standard deviation  for English is: 18.6269


The mode for subjects is: [[0 0 0 0 0]]
The minimum  for Maths is : 0 
The minimum  for Physics is : 0 
The minimum  for Chemistry is : 0 
The minimum  for Sciology is : 0 
The minimum  for English is : 0 


The maximum  for Maths is : 45 
The maximum  for Physics is : 50 
The maximum  for Ch

In [70]:
#Question 17.D)
#Question Print the current score card for the class

print("The Score card for Rajesh is: ")
for x in range(len(list1)):
    print(list1[x], marks2[0][x])
    
print("\n")

print("The Score card for Rima is: ")
for x in range(len(list1)):
    print(list1[x], marks2[1][x])
print("\n")
    
print("The Score card for Ram is: ")
for x in range(len(list1)):
    print(list1[x], marks2[2][x])
print("\n")

print("The Score card for Joseph is: ")
for x in range(len(list1)):
    print(list1[x], marks2[3][x])

The Score card for Rajesh is: 
Maths 15
Physics 20
Chemistry 25
Sciology 12
English 40


The Score card for Rima is: 
Maths 45
Physics 50
Chemistry 50
Sciology 48
English 49


The Score card for Ram is: 
Maths 8
Physics 7
Chemistry 3
Sciology 2
English 10


The Score card for Joseph is: 
Maths 28
Physics 32
Chemistry 40
Sciology 39
English 35
