In [3]:
#Question 1
#Create a vector or array of 100 elements. Its 50th value should be    50.0 and other values should be 0.0

import numpy as np

arr=np.zeros(100)
arr[49]=50.0
print("The array with 50th value with value 50 is:\n",arr)

The array with 50th value with value 50 is:
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.  50.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [6]:
#Queston 2
#Create a vector or array of 100 elements. Its 50th value should be    10.0 and other values should be 1.0

arr1=np.zeros(100)
arr1[49]=10.0
print("The array with 50th value with value 10 is:\n",arr1)

The array with 50th value with value 10 is:
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.  10.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [7]:
#Question 3
# Create a  vector or array whose values are from 3, 30

arr2=np.arange(3,31)
print("The array with value 3 to 30 is:",arr2)

The array with value 3 to 30 is: [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30]


In [9]:
#Question 4
# Reverse and print X

x=np.arange(5)
y=x[-1::-1]
print("The array after reversing is:",y)

The array after reversing is: [4 3 2 1 0]


In [9]:
#Question 5
#Create a 5x 5 matrix and values should be from 0 to 24

arr3=np.arange(0,25).reshape(5,5)
print("The array is :\n",arr3)

The array is :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
#Question 6

a1=np.array([[1,3,0],[2,1,1],[3,4,0]])
a2=np.array([[3,4,6],[2,1,3],[1,2,8]])
print("The array is:\n",a1)

print("The array is:\n",a2)

[[1 3 0]
 [2 1 1]
 [3 4 0]]
[[3 4 6]
 [2 1 3]
 [1 2 8]]


In [27]:
#Question 6,a
#a) Find min. max of the values for A1 and A2

print("The min value for a1 is:",a1.min())
print("The min value for a2 is:",a2.min())
print("The max value for a1 is:",a1.max())
print("The max value for a2 is:",a2.max())

The min value for a1 is: 0
The min value for a2 is: 1
The max value for a1 is: 4
The max value for a2 is: 8


In [28]:
#Q.6.b
#b) Find the mean value for A1 and A2

print("The mean of a1 is:",a1.mean())
print("The mean of a2 is:",a2.mean())

The mean of a1 is: 1.66666666667
The mean of a2 is: 3.33333333333


In [13]:
#Q.6.d
#Multiply A1 and A2

res=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(a1)):
    for j in range(len(a2[0])):
        for k in range(len(a2)):
            res[i][j]+=a1[i][k]*a2[k][j]
print("The resultant matrix is:")
for x in res:
    print(x)


The resultant matrix is:
[9, 7, 15]
[9, 11, 23]
[17, 16, 30]


In [34]:
#Q.6.f
#Swap first and 3rd rows of A1

temp=a1[0]
a1[0]=a1[2]
a1[2]=temp
print("The array after swapping is:\n",a1)

The array after swapping is:
 [[3 4 0]
 [2 1 1]
 [3 4 0]]


In [43]:
#Q.6,h
#Add a column to A1 with values 1 1 1 

arr5=np.array([1,1,1]).reshape(3,1)
#a=np.insert(a1,2,1,axis=1)
a=np.append(a1,arr5,axis=1)
print("The value after adding the last column is:\n",a)

The value after adding the last column is:
 [[3 4 0 1]
 [2 1 1 1]
 [3 4 0 1]]


In [56]:
#Q.6,i
#Add a row to A2 with 2 2 2

arr6=np.array([2,2,2]).reshape(1,3)
#b=a1.shape
#print(b)
a=np.append(a1,arr6,axis=0)
print("The value after adding a row is:\n",a)

The value after adding a row is:
 [[3 4 0]
 [2 1 1]
 [3 4 0]
 [2 2 2]]


In [6]:
#Question 7
# Write a function for matrix multiplications and additions. Use A1 and A2 to test.[3 marks]

def mul(a1,a2):
    res=[[0,0,0],[0,0,0],[0,0,0]] 
    for i in range(len(a1)):
        for j in range(len(a2[0])):
            for k in range(len(a2)):
                res[i][j]+=a1[i][k]*a2[k][j]
    print("The resultant matrix is:")
    for x in res:
        print(x)

def add(a1,a2):
    res=[[0,0,0],[0,0,0],[0,0,0]] 
    res=a1+a2
    print("the resultant matrix is:")
    for x in res:
          print(x)
    

print("1.multiplication 2.addition")
ch=int(input("Enter the choice:"))
if(ch==1):
    mul(a1,a2)
else:
    add(a1,a2)

1.multiplication 2.addition
Enter the choice:2
the resultant matrix is:
[4 7 6]
[4 2 4]
[4 6 8]


In [5]:
#Question 8
#Write a bubble sort program with normal Python  for 10 floating point numbers
def bubble(arr):
    len1=len(arr)
    for i in range(len1):
        for j in range(0,len1-i-1):
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                #arr[j+1]=arr[j]

arr=[2.0,1.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
bubble(arr)

print("The sorted array is:")
for i in range(len(arr)):
    print("%d"%arr[i])

The sorted array is:
1
2
3
4
5
6
7
8
9
10


In [8]:
#Question 6.c
#c) Make the values below the diagonal as 0.0 for A1

a1[1][0]=0.0
a1[2][0]=0.0
a1[2][1]=0.0
print(a1)

[[1 3 0]
 [0 1 1]
 [0 0 0]]


In [12]:
#Question 6.e
#What are the common values between A1 and A2

print("The common values are:",np.intersect1d(a1,a2))

The common values are: [1 3]


In [14]:
counts = np.bincount(a1)
print (np.argmax(counts))

ValueError: object too deep for desired array